#You can use hex code
special_fishing_rods:
  # This is the name of the fishing rod
  # This name is what you'll use to give yourself the fishing rod
  granite:
    # This is the visual name the fishing rod will have
    display_name: "#FF5733Granite Fishing Rod"
    # Here you can add a custom description
    lore:
      - "&7A special fishing rod"
      - "&7Made of granite"
    # This category is for configuring the items that have a chance to drop
    # There's no minimum value, but the maximum they can sum to is 100%
    drops:
      # Name of the item that will drop. This option is mandatory
      # The name must be the one the item has in the game
      - item: DIAMOND
        # Probability of this item dropping
        chance: 50.0
        # The visual name the item will have
        display_name: "#FF5733Brilliant Diamond"
        # The description of the item (optional)
        lore:
          - "&7A very shiny diamond"
          - "&7Perfect for your adventures"
        # The enchantments on the item (optional)
        enchantments:
          - SHARPNESS:5
        # The number of items that will drop (optional)
        quantity: 5
        # The particles that will appear around the player when they fish the item (optional)
        particles:
          type: "FLAME"
          amount: 10
        # The title that will appear when the item is caught (optional)
        title:
          text: "&6Congratulations!"
          subtitle: "You caught a Brilliant Diamond"
        # The sound that will play when the item is caught (optional)
        sound:
          type: "ENTITY_PLAYER_LEVELUP"
          volume: 1.0
          pitch: 1.0
      - item: GOLD_INGOT
        chance: 50.0
        display_name: "Golden Ingot"
        lore:
          - "&7A pure golden ingot"
          - "&7Use it wisely"
        quantity: 1
        particles:
          type: "SPELL_WITCH"
          amount: 15
        title:
          text: "&eGolden Ingot"
          subtitle: "A golden prize!"
        sound:
          type: "BLOCK_ANVIL_LAND"
          volume: 1.0
          pitch: 0.8
  obsidian:
    display_name: "&#FFF733Obsidian Fishing Rod"
    lore:
      - "&7Forged with obsidian"
      - "&7It's resistant and powerful"
    drops:
      - item: NETHERITE_SWORD
        chance: 30.0
        display_name: "Netherite Sword"
        lore:
          - "&7A very powerful sword"
          - "&7With ancient magic"
        enchantments:
          - LOOTING:3
        particles:
          type: "LAVA"
          amount: 20
        title:
          text: "&4Netherite Sword"
          subtitle: "A powerful sword!"
        sound:
          type: "ENTITY_WITHER_DEATH"
          volume: 1.0
          pitch: 1.0
