special_fishing_rods:
  granito:
    display_name: "§x#FF5733Caña de Pescar Granito"
    lore:
      - "§7Una caña de pescar especial"
      - "§7Hecha de granito"
    drops:
      - item: DIAMOND
        chance: 50.0
        display_name: "Diamante Brillante"
        lore:
          - "§7Un diamante muy brillante"
          - "§7Perfecto para tus aventuras"
        enchantments:
          - SHARPNESS:5
        quantity: 5
        particles:
          type: "FLAME"  # Tipo de partícula
          amount: 10      # Cantidad de partículas
        title:
          text: "§6¡Felicidades!"
          subtitle: "Has pescado un Diamante Brillante"
        sound:
          type: "ENTITY_PLAYER_LEVELUP"  # Tipo de sonido
          volume: 1.0
          pitch: 1.0
      - item: GOLD_INGOT
        chance: 50.0
        display_name: "Lingote Dorado"
        lore:
          - "§7Un lingote dorado puro"
          - "§7Utilízalo sabiamente"
        quantity: 1
        particles:
          type: "SPELL_WITCH"
          amount: 15
        title:
          text: "§eLingote Dorado"
          subtitle: "¡Un premio dorado!"
        sound:
          type: "BLOCK_ANVIL_LAND"
          volume: 1.0
          pitch: 0.8
  obsidiana:
    display_name: "§xCaña de Pescar Obsidiana"
    lore:
      - "§7Forjada con obsidiana"
      - "§7Es resistente y poderosa"
    drops:
      - item: NETHERITE_SWORD
        chance: 30.0
        display_name: "Espada de Netherite"
        lore:
          - "§7Una espada muy poderosa"
          - "§7Con una magia ancestral"
        enchantments:
          - LOOTING:3
        particles:
          type: "LAVA"
          amount: 20
        title:
          text: "§4Espada de Netherite"
          subtitle: "¡Una espada poderosa!"
        sound:
          type: "ENTITY_WITHER_DEATH"
          volume: 1.0
          pitch: 1.0
